"""PDF + CSV report generation for client performance."""
from __future__ import annotations

import csv
import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def csv_export(rows: list[dict[str, Any]]) -> bytes:
    if not rows:
        return b""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    for r in rows:
        writer.writerow(r)
    return buf.getvalue().encode("utf-8")


def pdf_report(
    *,
    agency_name: str,
    client_name: str,
    summary: dict[str, Any],
    per_platform: dict[str, dict[str, float]],
    brand_primary: str = "#E0115F",
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=f"{client_name} · Performance report",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=colors.HexColor(brand_primary),
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Heading3"],
        fontSize=12,
        textColor=colors.HexColor("#555555"),
        spaceAfter=18,
    )

    story: list[Any] = []
    story.append(Paragraph(f"{client_name} · Performance report", title_style))
    story.append(
        Paragraph(
            f"Generated by {agency_name} on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            subtitle_style,
        )
    )
    story.append(Spacer(1, 6))

    # Summary box
    kpi_rows = [
        ["Followers", f"{int(summary.get('total_followers', 0)):,}"],
        ["Impressions", f"{int(summary.get('total_impressions', 0)):,}"],
        ["Reach", f"{int(summary.get('total_reach', 0)):,}"],
        ["Engagement", f"{int(summary.get('total_engagement', 0)):,}"],
        ["Clicks", f"{int(summary.get('total_clicks', 0)):,}"],
        ["Conversions", f"{int(summary.get('total_conversions', 0)):,}"],
        ["Spend", f"€{float(summary.get('total_spend', 0)):.2f}"],
        ["Engagement rate", f"{float(summary.get('engagement_rate', 0)) * 100:.2f}%"],
    ]
    t = Table(kpi_rows, colWidths=[6 * cm, 8 * cm])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F5F5F5")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#111111")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 11),
                ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.white, colors.HexColor("#FAFAFA")]),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#EEEEEE")),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 16))

    # Per platform breakdown
    story.append(Paragraph("<b>Per-platform performance</b>", styles["Heading3"]))
    header = ["Platform", "Impressions", "Reach", "Engagement", "Clicks", "Spend"]
    data = [header]
    for plat, m in per_platform.items():
        data.append(
            [
                plat.title(),
                f"{int(m.get('impressions', 0)):,}",
                f"{int(m.get('reach', 0)):,}",
                f"{int(m.get('engagement', 0)):,}",
                f"{int(m.get('clicks', 0)):,}",
                f"€{float(m.get('spend', 0)):.2f}",
            ]
        )
    pt = Table(data, hAlign="LEFT")
    pt.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(brand_primary)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFAFA")]),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#EEEEEE")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(pt)
    story.append(Spacer(1, 20))
    story.append(
        Paragraph(
            "<i>This report was generated automatically by Rosa Road Studio. "
            "Metrics are pulled directly from connected platforms when credentials "
            "are available, or simulated for demonstration otherwise.</i>",
            styles["Italic"],
        )
    )
    doc.build(story)
    return buf.getvalue()
